In [51]:
import numpy as np
import gurobipy as gp
from gurobipy import Model, GRB, quicksum

In [54]:
model = gp.Model('Intento')
y = model.addVars([1,2], lb = 0, vtype = GRB.CONTINUOUS)
obj = np.array([-24,-28])
model.modelSense = GRB.MINIMIZE
model.setObjective( quicksum(y[a]*obj[a-1] for a in range(1,3)) )

lhs_ineq = np.array([[6,10],[8,5],[1,0],[0,1]])
rhs_ineq = np.array([2400,1600,500,100])

model.addMConstr (lhs_ineq, x = None, sense='<=', b = rhs_ineq, name="cons" )
model.optimize()
print("\nResultado:\n")
print(y,"\n")
print("Pi del modelo: \n")
print(model.pi)
print("Optimal objective\n", model.objval)

Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 4 rows, 2 columns and 6 nonzeros
Model fingerprint: 0xb42b4eb3
Coefficient statistics:
  Matrix range     [1e+00, 1e+01]
  Objective range  [2e+01, 3e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+02, 2e+03]
Presolve removed 4 rows and 2 columns
Presolve time: 0.01s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -6.1000000e+03   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.01 seconds
Optimal objective -6.100000000e+03

Resultado:

{1: <gurobi.Var C0 (value 137.5)>, 2: <gurobi.Var C1 (value 100.0)>} 

Pi del modelo: 

[0.0, -3.0, 0.0, -13.0]
Optimal objective
 -6100.0


In [13]:
#Ejemplo
#Ejemplo
c = np.array([100,150,0,0,0])
A = np.array([[1,1,1,0,0],[1,0,0,-1,0],[0,1,0,0,-1]])
b = np.array([120,40,20])

problemaMaestro(np.array([]), np.array([]), c, A, b)

#Rta debería ser: (40,20) y theta = -inf

NameError: name 'problemaMaestro' is not defined

In [2]:
#Ejemplo caso 2:

E = np.array([[83.52, 180.48, 0,0,0,-520]])

c = np.array([100,150,0,0,0])
A = np.array([[1,1,1,0,0],[1,0,0,-1,0],[0,1,0,0,-1]])
b = np.array([120,40,20])


rta = problemaMaestro(np.array([]), E, c, A, b)
print(rta)

#Rta debería ser: (40,80) y  theta = -18299.2

NameError: name 'problemaMaestro' is not defined

In [11]:
a = np.array([3,2,1])
b = np.append(a,np.array([4]))
b

array([3, 2, 1, 4])

In [43]:
np.append(np.full(7,9),np.zeros(12))

array([9., 9., 9., 9., 9., 9., 9., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [49]:
a = np.array( [3,2,1] )
b = np.array( [4,4,2] )
print(a <= b )
np.all(a <= b)

[ True  True  True]


True

In [50]:
q = np.append(np.full(7,9),np.zeros(12))
q.size

19

In [56]:
np.isnan(np.nan)

True

In [86]:
#Funciona: x in K2

k = 0
W= np.array([ [3,2,1,0,0,0,0,0],[2,5,0,1,0,0,0,0],[1,0,0,0,-1,0,0,0],[0,1,0,0,0,-1,0,0],[1,0,0,0,0,0,1,0],[0,1,0,0,0,0,0,1] ])
q = np.array( [15,12,0,0,0,0,0,0] )

print(W)

#Itero sobre todas las posibles realizaciones de \zeta:
hact = np.array([0,0,4.8,6.4,6,8])
bact = hact 

model = gp.Model('Auxiliar')

vary = model.addVars(range(0,q.size), lb = 0, vtype = GRB.CONTINUOUS, name='vary')
vmas = model.addVars(range(0,W.shape[0]), lb = 0, vtype = GRB.CONTINUOUS, name = 'vmas')
vmenos = model.addVars(range(0,W.shape[0]), lb = 0, vtype = GRB.CONTINUOUS, name = 'vmenos')

model.modelSense = GRB.MINIMIZE
model.setObjective( quicksum(vmas[a] + vmenos[a]  for a in range(0,W.shape[0])) )

Waux = np.hstack( (W, np.identity(W.shape[0]), -np.identity(W.shape[0])) )

model.addMConstr( Waux, x=None, sense='=', b = bact, name="constr" )

model.optimize()




[[ 3  2  1  0  0  0  0  0]
 [ 2  5  0  1  0  0  0  0]
 [ 1  0  0  0 -1  0  0  0]
 [ 0  1  0  0  0 -1  0  0]
 [ 1  0  0  0  0  0  1  0]
 [ 0  1  0  0  0  0  0  1]]
Gurobi Optimizer version 9.1.2 build v9.1.2rc0 (win64)
Thread count: 2 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 6 rows, 20 columns and 26 nonzeros
Model fingerprint: 0xbb5f8a5f
Coefficient statistics:
  Matrix range     [1e+00, 5e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [5e+00, 8e+00]
Presolve removed 6 rows and 20 columns
Presolve time: 0.02s
Presolve: All rows and columns removed
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0    1.1200000e+01   0.000000e+00   0.000000e+00      0s

Solved in 0 iterations and 0.04 seconds
Optimal objective  1.120000000e+01


In [85]:
W= np.array([ [3,2,1,0,0,0,0,0],[2,5,0,1,0,0,0,0],[1,0,0,0,-1,0,0,0],[0,1,0,0,0,-1,0,0],[1,0,0,0,0,0,1,0],[0,1,0,0,0,0,0,1] ])

print(W.shape[0])

Wact = np.hstack( (W, np.identity(W.shape[0]), -np.identity(W.shape[0])) )
Wact

6


array([[ 3.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0., -1., -0., -0., -0., -0., -0.],
       [ 2.,  5.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0., -0., -1., -0., -0., -0., -0.],
       [ 1.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,
         0., -0., -0., -1., -0., -0., -0.],
       [ 0.,  1.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0., -0., -0., -0., -1., -0., -0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
         0., -0., -0., -0., -0., -1., -0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         1., -0., -0., -0., -0., -0., -1.]])